// v54 — הגשר המובנה באפליקציה (בלי פייתון): שלט טלפון, חדר, אורח, /health
import path from 'path'; import fs from 'fs'; import os from 'os'; import { createRequire } from 'module'; import { fileURLToPath } from 'url';
import {ok,done} from './h.mjs';
const HERE=path.dirname(fileURLToPath(import.meta.url)); const require=createRequire(import.meta.url);
const { Bridge } = require(path.resolve(HERE,'../app/bridge.js'));
const WebSocket = require(path.resolve(HERE,'../app/node_modules/ws'));
const D=fs.mkdtempSync(path.join(os.tmpdir(),'bbbr-'));
const b=new Bridge({port:9671,dataDir:D,simPath:path.resolve(HERE,'../dist/BIOBUZZ-lab-lite.html'),padPath:path.resolve(HERE,'../app/pad/pad.html')});
ok(await b.start(),'הגשר עלה על 9671');
const b2=new Bridge({port:9671,dataDir:D}); ok(!(await b2.start())&&/תפוס/.test(b2.error),'פורט תפוס — הודעה ברורה: '+b2.error);
const h=await (await fetch('http://127.0.0.1:9671/health')).json();
ok(h.ok&&h.app&&h.port===9671,'/health עונה');
ok((await fetch('http://127.0.0.1:9671/')).status===200,'דף השלט לטלפון');
ok((await fetch('http://127.0.0.1:9671/sim')).status===200,'הסימולטור מהגשר');
ok((await fetch('http://127.0.0.1:9671/join?k=1')).status===403,'הצטרפות בלי קוד — נחסם');
const open=(q)=>new Promise((res,rej)=>{ const w=new WebSocket('ws://127.0.0.1:9671/ws?'+q); w.msgs=[]; w.on('message',(d,bin)=>w.msgs.push(bin?d:d.toString())); w.on('open',()=>res(w)); w.on('error',rej); w.on('unexpected-response',(q2,r)=>rej(new Error('HTTP '+r.statusCode))); });
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const sim=await open('role=sim'); await wait(100);
ok(sim.msgs.some(m=>/"t":"pad","on":false/.test(m)),'הסימולטור מקבל ״אין טלפון״');
const pad=await open('role=pad'); await wait(100);
ok(sim.msgs.some(m=>/"t":"pad","on":true/.test(m)),'טלפון התחבר → הסימולטור יודע');
pad.send('{"t":"in","x":0.5}'); await wait(100);
ok(sim.msgs.some(m=>/"t":"in"/.test(m)),'קלט מהטלפון מגיע לסימולטור');
sim.send('{"t":"q","id":1}'); await wait(100);
ok(pad.msgs.some(m=>/"t":"q"/.test(m)),'הודעה מהסימולטור מגיעה לטלפון');
const host=await open('role=host'); await wait(100);
ok(host.msgs.some(m=>/"t":"info"/.test(m)&&/"key":/.test(m)),'מארח מקבל פרטי חדר');
let bad=null; try{ await open('role=guest&k=0'); }catch(e){ bad=e; } ok(!!bad,'אורח עם מפתח שגוי — נחסם');
const g=await open('role=guest&k='+b.key+'&n=נועה'); await wait(150);
ok(host.msgs.some(m=>/"t":"gj"/.test(m)&&/נועה/.test(m)),'אורח הצטרף — המארח יודע');
g.send('{"t":"in","x":1}'); await wait(100);
ok(host.msgs.some(m=>/"t":"g","id":"g1"/.test(m)),'קלט האורח מגיע למארח');
host.send(Buffer.from([1,2,3]),{binary:true}); await wait(100);
ok(g.msgs.some(m=>Buffer.isBuffer(m)&&m.length===3),'מצב הזירה (בינארי) מגיע לאורח');
host.close(); await wait(150);
ok(g.msgs.some(m=>/"t":"nohost"/.test(m)),'המארח יצא — האורח יודע');
for(const w of [sim,pad,g]) w.close();
b.stop(); fs.rmSync(D,{recursive:true,force:true});
done('bridge_test');
